### ISSUE TITLE
RecyclerView下使用崩溃

### ISSUE THREAD

**Issue by wheatdamon** [huzenan/EasyTransition#2]
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.getLocationOnScreen(int[])' on a null object reference
                                                                           at com.escher.magicworld.utils.EasyTransition.runExitAnimation(EasyTransition.java:193)
                                                                           at com.escher.magicworld.utils.EasyTransition.exit(EasyTransition.java:156)
                                                                           at com.escher.magicworld.utils.EasyTransition.exit(EasyTransition.java:180)
                                                                           at com.escher.magicworld.activity.DiscoveryDetailActivity.onBackPressed(DiscoveryDetailActivity.java:32)

**Comment by huzenan** [comment]
这是退出时找不到对应于上一个Activity中的View，才导致获取位置时报了空指针，检查一下两个View的id是不是一致的呢？
