### ISSUE TITLE
null pointer exception

### ISSUE THREAD

**Issue by raj123456789123456789** [huzenan/EasyTransition#7]
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.getLocationOnScreen(int[])' on a null object reference
at com.world.utils.EasyTransition.runExitAnimation(EasyTransition.java:193)
at com.world.utils.EasyTransition.exit(EasyTransition.java:156)
at com.world.utils.EasyTransition.exit(EasyTransition.java:180)
at com.world.activity.DetailActivity.onBackPressed(DetailActivity.java:32)

**Comment by siyehua** [comment]
看源码，这个退出的时候的 Activity 是 B，此时用 B 去查找 A 的 View，自然会闪退。
所以这个库要求两个 Activity 使用同样的 id
